# Generated by Django 5.0.3 on 2024-03-28 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('num_of_seats', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='BookingRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('room', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='rooms.room')),
            ],
        ),
    ]
