services:
  db:
    image: postgres:16.0
    volumes:
      - python_test_task3-volume:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - python_test_task3-network
    container_name: python_test_task3_db
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'" ]
      interval: 10s
      timeout: 3s
      retries: 3

  web:
    build: .
    ports:
      - '8000:8000'
    container_name: django
    depends_on:
      db:
        condition: service_healthy
    networks:
      - python_test_task3-network
    restart: always

volumes:
  python_test_task3-volume:

networks:
  python_test_task3-network:
